version: '3.8'

services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
    command: ["-p", "4222", "-m", "8222"]

volumes:
  psql_volume:
